# Generated by Django 2.0.2 on 2018-03-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamo',
            old_name='estador',
            new_name='estado',
        ),
    ]
