# Generated by Django 2.0.2 on 2018-03-07 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180306_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reclamo',
            name='subcategotia',
        ),
        migrations.AddField(
            model_name='reclamo',
            name='subcategoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategoria', to='api.Subcategoria'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria', to='api.Categoria'),
        ),
    ]
