# Generated by Django 2.0.2 on 2018-03-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180307_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='imagem',
            new_name='imagen',
        ),
    ]
